apiVersion: v1
kind: Pod
metadata:
  name: azure-test
  namespace: default
spec:
  containers:
    - name: pythonapp
      image: demoacrnew.azurecr.io/mypythonapp
  imagePullSecrets:
    - name: demoacrnew